package me.chan.texas.ext.markdown.math.renderer.fonts;

import java.util.HashMap;
import java.util.Map;

import me.chan.texas.ext.markdown.math.ast.ExtensibleArrowAtom;
import me.chan.texas.ext.markdown.math.ast.SymbolAtom;
import me.chan.texas.ext.markdown.math.ast.GreekLetterVariableAtom;
import me.chan.texas.ext.markdown.math.ast.LargeOperatorAtom;

public class MathFontOptions {
	public static final float UNITS_PER_EM = 1000F;
	public static final float RADICAL_VERTICAL_GAP = 50;
	public static final float RADICAL_RULE_THICKNESS = 40;
	public static final float RADICAL_EXTRA_ASCENDER = 40;
	public static final float RADICAL_KERN_BEFORE_DEGREE = 278;
	public static final float RADICAL_DEGREE_BOTTOM_RAISE_PERCENT = 60;
	public static final float FRACTION_NUMERATOR_GAP_MIN = 40;
	public static final float FRACTION_RULE_THICKNESS = 40;
	public static final float FRACTION_DENOMINATOR_GAP_MIN = 40;

	private static final SymbolOptions SYMBOL = new SymbolOptions();
	private static final Map<String, String> AST = new HashMap<>();
	private static final Map<String, String> TEXT_OPERATORS = new HashMap<>();

	static {
		AST.put("rceil", "⌉");
		AST.put("varphi", "φ");
		AST.put("supseteq", "⊇");
		AST.put("xtwoheadrightarrow", "↠");
		AST.put("angleleft", "〈");
		AST.put("parenright", ")");
		AST.put("ring", "˚");
		AST.put("logicaland", "∧");
		AST.put("approxequal", "≈");
		AST.put("asterisk", "*");
		AST.put("wedge", "∧");
		AST.put("rightarrow", "→");
		AST.put("delta", "δ");
		AST.put("notequal", "≠");
		AST.put("bigcup", "⋃");
		AST.put("uni25C1", "◁");
		AST.put("theta", "θ");
		AST.put("dddotaccent", "˙˙˙");
		AST.put("lambda", "λ");
		AST.put("bar", "|");
		AST.put("prec", "≺");
		AST.put("checkmark", "✓");
		AST.put("leq", "≤");
		AST.put("Pi", "Π");
		AST.put("triangleright", "▷");
		AST.put("because", "∵");
		AST.put("breve", "˘");
		AST.put("element", "∈");
		AST.put("models", "⊨");
		AST.put("iota", "ι");
		AST.put("equivalence", "≡");
		AST.put("xhookleftarrow", "↩");
		AST.put("Rfraktur", "ℜ");
		AST.put("cdot", "⋅");
		AST.put("proportional", "∝");
		AST.put("similar_equal", "≃");
		AST.put("langle", "〈");
		AST.put("greatermuch", "≫");
		AST.put("cup", "∪");
		AST.put("varnothing", "∅");
		AST.put("odot", "⊙");
		AST.put("mid", "∣");
		AST.put("sum", "∑");
		AST.put("asciicircum", "^");
		AST.put("Re", "ℜ");
		AST.put("bigodot", "⨀");
		AST.put("integral", "∫");
		AST.put("uni219E", "↞");
		AST.put("nexists", "∄");
		AST.put("arrowright", "→");
		AST.put("star", "⋆");
		AST.put("dots", "…");
		AST.put("uni25B7", "▷");
		AST.put("forall", "∀");
		AST.put("circledivide", "⊘");
		AST.put("union", "∪");
		AST.put("emptyset", "∅");
		AST.put("setminus", "∖");
		AST.put("asciitilde", "~");
		AST.put("succ", "≻");
		AST.put("Delta", "Δ");
		AST.put("contourintegral", "∮");
		AST.put("infinity", "∞");
		AST.put("to", "→");
		AST.put("implies", "⇒");
		AST.put("gamma", "γ");
		AST.put("uni2296", "⊖");
		AST.put("quotesingle", "'");
		AST.put("rfloor", "⌋");
		AST.put("coprod", "∐");
		AST.put("propto", "∝");
		AST.put("uni27C2", "⟂");
		AST.put("cdots", "⋯");
		AST.put("summation", "∑");
		AST.put("div", "÷");
		AST.put("existential", "∃");
		AST.put("bigwedge", "⋀");
		AST.put("ldots", "…");
		AST.put("intersection", "∩");
		AST.put("varrho", "ϱ");
		AST.put("hbar", "ℏ");
		AST.put("aleph", "ℵ");
		AST.put("sigma", "σ");
		AST.put("oiiint", "∰");
		AST.put("ell", "ℓ");
		AST.put("chi", "χ");
		AST.put("Psi", "Ψ");
		AST.put("exclam", "!");
		AST.put("Theta", "Θ");
		AST.put("succeq", "⪰");
		AST.put("xleftarrow", "←");
		AST.put("therefore", "∴");
		AST.put("reflexsuperset", "⊇");
		AST.put("xmapsto", "↦");
		AST.put("xleftrightarrow", "↔");
		AST.put("perp", "⟂");
		AST.put("psi", "ψ");
		AST.put("Sigma", "Σ");
		AST.put("bigsqcup", "⨆");
		AST.put("daggerdbl", "‡");
		AST.put("sim", "∼");
		AST.put("divides", "∣");
		AST.put("uni227B", "≻");
		AST.put("iint", "∬");
		AST.put("alpha", "α");
		AST.put("uni227A", "≺");
		AST.put("oplus", "⊕");
		AST.put("wp", "℘");
		AST.put("divide", "÷");
		AST.put("bullet", "•");
		AST.put("multiply", "×");
		AST.put("braceleft", "{");
		AST.put("Lambda", "Λ");
		AST.put("ge", "≥");
		AST.put("gg", "≫");
		AST.put("zeta", "ζ");
		AST.put("ddotaccent", "˙˙");
		AST.put("iff", "⇔");
		AST.put("varepsilon", "ε");
		AST.put("equal", "=");
		AST.put("xi", "ξ");
		AST.put("Ifraktur", "ℑ");
		AST.put("bracketright", "]");
		AST.put("ddagger", "‡");
		AST.put("rho", "ρ");
		AST.put("ominus", "⊖");
		AST.put("subset", "⊂");
		AST.put("nabla", "∇");
		AST.put("logicalnot", "¬");
		AST.put("xLeftarrow", "⇐");
		AST.put("bowtie", "⋈");
		AST.put("cong", "≅");
		AST.put("braceright", "}");
		AST.put("uni224D", "≍");
		AST.put("uni21C4", "⇄");
		AST.put("arrowdblleft", "⇐");
		AST.put("epsilon", "ϵ");
		AST.put("circledot", "⊙");
		AST.put("Xi", "Ξ");
		AST.put("oint", "∮");
		AST.put("sqrt", "√");
		AST.put("uni22F1", "⋱");
		AST.put("lessequal", "≤");
		AST.put("greaterequal", "≥");
		AST.put("bigotimes", "⨂");
		AST.put("uni22EF", "⋯");
		AST.put("greater", ">");
		AST.put("uni22EE", "⋮");
		AST.put("ddots", "⋱");
		AST.put("uni2015", "―");
		AST.put("similar", "∼");
		AST.put("Leftarrow", "⇐");
		AST.put("in", "∈");
		AST.put("nmid", "∤");
		AST.put("arrowdblright", "⇒");
		AST.put("omega", "ω");
		AST.put("iiint", "∭");
		AST.put("xtofrom", "⇄");
		AST.put("circ", "∘");
		AST.put("lfloor", "⌊");
		AST.put("bigoplus", "⨁");
		AST.put("partial", "∂");
		AST.put("uni2230", "∰");
		AST.put("uni21AA", "↪");
		AST.put("Im", "ℑ");
		AST.put("simeq", "≃");
		AST.put("uni22C8", "⋈");
		AST.put("uni210F", "ℏ");
		AST.put("uni2A06", "⨆");
		AST.put("uni222F", "∯");
		AST.put("uni21A6", "↦");
		AST.put("uni21A9", "↩");
		AST.put("varsigma", "ς");
		AST.put("Upsilon", "Υ");
		AST.put("uni2A02", "⨂");
		AST.put("uni222C", "∬");
		AST.put("uni22C3", "⋃");
		AST.put("uni2A01", "⨁");
		AST.put("uni22C6", "⋆");
		AST.put("uni2A04", "⨄");
		AST.put("uni22C5", "⋅");
		AST.put("uni222D", "∭");
		AST.put("Phi", "Φ");
		AST.put("subseteq", "⊆");
		AST.put("lceil", "⌈");
		AST.put("geq", "≥");
		AST.put("xtwoheadleftarrow", "↞");
		AST.put("preceq", "⪯");
		AST.put("angle", "∠");
		AST.put("kappa", "κ");
		AST.put("logicalor", "∨");
		AST.put("uni2113", "ℓ");
		AST.put("uni2AB0", "⪰");
		AST.put("product", "∏");
		AST.put("prod", "∏");
		AST.put("hyphen", "-");
		AST.put("uni2AAF", "⪯");
		AST.put("vdots", "⋮");
		AST.put("xRightarrow", "⇒");
		AST.put("phi", "ϕ");
		AST.put("parenleft", "(");
		AST.put("comma", ",");
		AST.put("arrowleft", "←");
		AST.put("weierstrass", "℘");
		AST.put("le", "≤");
		AST.put("exists", "∃");
		AST.put("notin", "∉");
		AST.put("propersuperset", "⊃");
		AST.put("arrowdblboth", "⇔");
		AST.put("xrightarrow", "→");
		AST.put("uni2245", "≅");
		AST.put("xLeftrightarrow", "⇔");
		AST.put("partialdiff", "∂");
		AST.put("ll", "≪");
		AST.put("plusminus", "±");
		AST.put("uni2210", "∐");
		AST.put("Leftrightarrow", "⇔");
		AST.put("biguplus", "⨄");
		AST.put("uni22A8", "⊨");
		AST.put("dotaccent", "˙");
		AST.put("leftarrow", "←");
		AST.put("xhookrightarrow", "↪");
		AST.put("neg", "¬");
		AST.put("Gamma", "Γ");
		AST.put("eta", "η");
		AST.put("minusplus", "∓");
		AST.put("vee", "∨");
		AST.put("oiint", "∯");
		AST.put("uni2216", "∖");
		AST.put("uni2218", "∘");
		AST.put("neq", "≠");
		AST.put("oslash", "⊘");
		AST.put("dagger", "†");
		AST.put("mp", "∓");
		AST.put("uni2220", "∠");
		AST.put("bigvee", "⋁");
		AST.put("leftrightarrow", "↔");
		AST.put("upsilon", "υ");
		AST.put("mu", "μ");
		AST.put("tau", "τ");
		AST.put("less", "<");
		AST.put("plus", "+");
		AST.put("uni22C0", "⋀");
		AST.put("uni22C2", "⋂");
		AST.put("uni2A00", "⨀");
		AST.put("rangle", "〉");
		AST.put("uni22C1", "⋁");
		AST.put("uni21A0", "↠");
		AST.put("supset", "⊃");
		AST.put("Rightarrow", "⇒");
		AST.put("circleplus", "⊕");
		AST.put("lessmuch", "≪");
		AST.put("uni2224", "∤");
		AST.put("acute", "´");
		AST.put("bracketleft", "[");
		AST.put("uni23A9", "⎩");
		AST.put("uni23A8", "⎨");
		AST.put("nu", "ν");
		AST.put("uni23A5", "⎥");
		AST.put("uni23A4", "⎤");
		AST.put("otimes", "⊗");
		AST.put("uni23A7", "⎧");
		AST.put("uni23A6", "⎦");
		AST.put("varpi", "ϖ");
		AST.put("uni23A1", "⎡");
		AST.put("Omega", "Ω");
		AST.put("uni23A3", "⎣");
		AST.put("uni23A2", "⎢");
		AST.put("times", "×");
		AST.put("cap", "∩");
		AST.put("parallel", "∥");
		AST.put("arrowboth", "↔");
		AST.put("reflexsubset", "⊆");
		AST.put("uni23AD", "⎭");
		AST.put("triangleleft", "◁");
		AST.put("uni23AA", "⎪");
		AST.put("infty", "∞");
		AST.put("universal", "∀");
		AST.put("beta", "β");
		AST.put("uni23AC", "⎬");
		AST.put("semicolon", ";");
		AST.put("uni23AB", "⎫");
		AST.put("bigcap", "⋂");
		AST.put("propersubset", "⊂");
		AST.put("grave", "`");
		AST.put("asymp", "≍");
		AST.put("int", "∫");
		AST.put("ellipsis", "…");
		AST.put("angleright", "〉");
		AST.put("equiv", "≡");
		AST.put("vartheta", "ϑ");
		AST.put("uni2209", "∉");
		AST.put("circlemultiply", "⊗");
		AST.put("pi", "π");
		AST.put("uni2204", "∄");
		AST.put("slash", "/");
		AST.put("pm", "±");
		AST.put("approx", "≈");

		TEXT_OPERATORS.put("lim", "lim");
		TEXT_OPERATORS.put("limsup", "lim sup");
		TEXT_OPERATORS.put("liminf", "lim inf");
		TEXT_OPERATORS.put("sin", "sin");
		TEXT_OPERATORS.put("cos", "cos");
		TEXT_OPERATORS.put("tan", "tan");
		TEXT_OPERATORS.put("cot", "cot");
		TEXT_OPERATORS.put("sec", "sec");
		TEXT_OPERATORS.put("csc", "csc");
		TEXT_OPERATORS.put("log", "log");
		TEXT_OPERATORS.put("ln", "ln");
		TEXT_OPERATORS.put("lg", "lg");
		TEXT_OPERATORS.put("exp", "exp");
		TEXT_OPERATORS.put("max", "max");
		TEXT_OPERATORS.put("min", "min");
		TEXT_OPERATORS.put("sup", "sup");
		TEXT_OPERATORS.put("inf", "inf");
		TEXT_OPERATORS.put("det", "det");
		TEXT_OPERATORS.put("dim", "dim");
		TEXT_OPERATORS.put("gcd", "gcd");
		TEXT_OPERATORS.put("ker", "ker");
	}

	public static Symbol symbol(String c) {
		return ref(c);
	}

	public static Symbol symbol(LargeOperatorAtom atom) {
		String symbol = atom.name;
		String ref = AST.get(symbol);
		if (ref != null) {
			return SYMBOL.all.get(ref);
		}
		return null;
	}

	public static String ast(GreekLetterVariableAtom atom) {
		return AST.get(atom.name);
	}

	public static Symbol ast(SymbolAtom atom) {
		String symbol = atom.symbol;
		if (symbol.startsWith("\\")) {
			return ref(atom.symbol.substring(1));
		}

		return SYMBOL.all.get(symbol);
	}

	private static Symbol ref(String symbol) {
		String ref = AST.get(symbol);
		if (ref == null) {
			throw new IllegalArgumentException("Unknown symbol: " + symbol);
		}
		return SYMBOL.all.get(ref);
	}

	public static Symbol ast(ExtensibleArrowAtom atom) {
		return ref(atom.command);
	}

	public static String textOp(String name) {
		return TEXT_OPERATORS.get(name);
	}
}